#!/bin/bash
#SBATCH --job-name=LineupPositionTrainJobMixed56
#SBATCH --account=sk54
#SBATCH --time=144:00:00
#SBATCH --partition=gpu
#SBATCH --ntasks=6
#SBATCH --gres=gpu:1
#SBATCH --mem=100G

#SBATCH --mail-user=weihao.li@monash.edu
#SBATCH --mail-type=BEGIN,END,FAIL

source ~/.bashrc
conda activate tf
module load R/4.0.5

cd ~/sk54/patrickli/automatic_visual_inference
python scripts/lineup_position_sim_only/lineup_mixed_56.py

