#!/bin/bash
#SBATCH --job-name=SinglePlotNullOrNotTrainJobPoly
#SBATCH --account=sk54
#SBATCH --time=24:00:00
#SBATCH --partition=m3g
#SBATCH --ntasks=6
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

#SBATCH --mail-user=weihao.li@monash.edu
#SBATCH --mail-type=BEGIN,END,FAIL

source ~/.bashrc
conda activate tf
module load R/4.0.5

cd ~/sk54/patrickli/automatic_visual_inference
python scripts/single_plot_null_or_not_sim_only/single_plot_poly.py




