#!/bin/bash
#SBATCH --job-name=SinglePlotNullOrNotTrainJob
#SBATCH --account=sk54
#SBATCH --time=24:00:00
#SBATCH --partition=m3h
#SBATCH --ntasks=6
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

#SBATCH --mail-user=weihao.li@monash.edu
#SBATCH --mail-type=BEGIN,END,FAIL

module load R/4.0.5
module load cuda/10.1
module load cudnn/7.6.5.32-cuda10

cd ~/sk54/patrickli/automatic_visual_inference

Rscript scripts/single_plot_null_or_not_sim_only/single_plot_mixed.R



